<?php // phpcs:disable

/** @var $viewModel \CardknoxDevelopment\Cardknox\ViewModel\Data */
$viewModel = $block->getViewModel();
$isEnabledReCaptcha = $viewModel->isEnabledReCaptcha();
$selectReCaptchaSource = $viewModel->getSelectReCaptchaSource();


if ($isEnabledReCaptcha && $selectReCaptchaSource == "recaptcha.net") : ?>
    <script src="https://www.recaptcha.net/recaptcha/api.js" async defer></script>
<?php endif;?>