<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \CardknoxDevelopment\Cardknox\Block\GiftCard $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @see \CardknoxDevelopment\Cardknox\Block\GiftCard
 */
$isCardknoxGiftcardEnabled = $block->isCardknoxGiftcardEnabled();
$cardknoxGiftText = $block->cardknoxGiftcardText();

if ($isCardknoxGiftcardEnabled) {
    $giftcardCode = $block->getGiftCardCode();
    $giftcardAmount = $block->getGiftCardAmount();
    $isAppliedGiftcardCode = false;
    $disableField = "";
    if ($giftcardCode && $giftcardAmount) {
        $isAppliedGiftcardCode = true;
        $disableField = 'disabled=disabled';
    } ?>

    <div class="block giftcard"
            id="block-giftcard"
            data-mage-init='{"collapsible":{"active": true, "openedState": "active", "saveState": false}}'>
        <div data-role="title" class="title">
            <strong id="block-giftcard-heading" role="heading" aria-level="2">
                <?= $escaper->escapeHtml(__($cardknoxGiftText)) ?>
            </strong>
        </div>
        <div data-role="content" class="content" aria-labelledby="block-giftcard-heading">
            <div id="giftcard-balance-lookup"></div>
            <span id="gc-please-wait" class="please-wait load indicator"
                data-text="<?= $escaper->escapeHtmlAttr(__('This won\'t take long . . .')) ?>">
                <span><?= $escaper->escapeHtml(__('This won\'t take long . . .')) ?></span>
            </span>
            <?= /* @noEscape */ $secureRenderer->renderTag(
                'style',
                [],
                '#gc-please-wait { display: none;}',
                false
            ); ?>
            <form class="form giftcard add" id="giftcard-form"
                    action="#" method="post"
                    data-mage-init='{"validation": {},"giftCard": {
                    "giftCardCodeSelector": "#giftcard-code",
                    "giftCardFormSelector": "#giftcard-form",
                    "checkStatus": "#ck-giftcard-balance-check",
                    "giftCardStatusUrl": "<?= $escaper->escapeUrl($block->getCheckGiftCardBalanceUrl()) ?>",
                    "addGiftcardCodeBtn":"#giftcard-code-btn",
                    "addGiftCardUrl": "<?= $escaper->escapeUrl($block->getAddGiftCardUrl()) ?>",
                    "cancelGiftcardCodeBtn": "#giftcard-code-cancel-btn",
                    "cancelGiftCardUrl": "<?= $escaper->escapeUrl($block->getCancelGiftCardUrl()) ?>",
                    "giftCardStatusId": "#giftcard-balance-lookup",
                    "giftCardSpinnerId": "#gc-please-wait",
                    "messages": ".page.messages .messages"
                    }}'>
                <div class="fieldset">
                    <div class="field">
                        <label class="label" for="giftcard-code">
                            <span><?= $escaper->escapeHtml(__('Enter the gift card code')) ?></span>
                        </label>
                        <div class="control">
                            <input class="input-text" type="text" id="giftcard-code" name="giftcard_code"
                                    data-validate="{'required-entry':true}"
                                    value="<?= $escaper->escapeHtmlAttr($giftcardCode) ?>"
                                    <?= /* @noEscape */ $disableField ?>/>
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button class="action add primary"
                                    id="giftcard-code-btn"
                                    type="submit"
                                    value="<?= $escaper->escapeHtmlAttr(__('Add Gift Card')) ?>"
                                    style="<?= $isAppliedGiftcardCode ? 'display:none;' : 'display:block;' ?>">
                                <span><?= $escaper->escapeHtml(__('Add Gift Card')) ?></span>
                            </button>
                            <?php if ($isAppliedGiftcardCode == true):?>
                                <input class="input-text" type="hidden" name="giftcard_code"
                                    value="<?= $escaper->escapeHtmlAttr($giftcardCode) ?>"/>
                            <?php endif;?>
                            <button class="action add primary"
                                    id="giftcard-code-cancel-btn"
                                    type="submit"
                                    value="<?= $escaper->escapeHtmlAttr(__('Cancel')) ?>"
                                    style="<?= !$isAppliedGiftcardCode ? 'display:none;' : 'display:block;' ?>">
                                <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
                            </button>
                        </div>
                        <div class="secondary">
                            <button class="action check"
                                    id="ck-giftcard-balance-check"
                                    type="button"
                                    value="<?= $escaper->escapeHtmlAttr(__('Check Gift Card status and balance')) ?>">
                                <span><?= $escaper->escapeHtml(__('Check Gift Card status and balance')) ?></span>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php }?>