<?php // phpcs:disable

/** @var $viewModel \CardknoxDevelopment\Cardknox\ViewModel\Data */
$viewModel = $block->getViewModel();
$isActiveGooglePay = $viewModel->isActiveGooglePay();

if ($isActiveGooglePay) : ?>
    <div id="googlepay-btn-cart-summary" data-bind="scope: 'googlepay-btn-cart-summary'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "googlepay-btn-cart-summary": {
                            "component": "CardknoxDevelopment_Cardknox/js/view/cart/google-pay",
                            "template" : "CardknoxDevelopment_Cardknox/cart/google-pay-btn"
                        }
                    }
                }
            }
        }
    </script>
<?php endif;?>