<?php
/**
 * Copyright © 2024 Cardknox Development Inc. All rights reserved.
 * See LICENSE for license details.
 */

/**
 * @var CardknoxDevelopment\Cardknox\Block\Payment $block
 * @var \Magento\Framework\Escaper $escaper
 */

$code = $escaper->escapeHtml($block->getCode());?>
<script>
    //<![CDATA[
    require(
        [
            'jquery',
            'CardknoxDevelopment_Cardknox/cardknox',
            'ifields'
        ], function($, Cardknox) {
            var config = <?= /* @noEscape */ $block->getPaymentConfig(); ?>,
                payment,
                form =  $('#payment_form_<?= /* @noEscape */ $code; ?>');
            config.active = form.length > 0 && !form.is(':hidden');
            payment = new Cardknox(config);         
        });
    //]]>
</script>
