<?php
/**
 * Copyright © 2024 Cardknox Development Inc. All rights reserved.
 * See LICENSE for license details.
 */

/**
 * @var \Magento\Payment\Block\Adminhtml\Transparent\Form $block
 * @var \Magento\Framework\Escaper $escaper
 */
$code = $escaper->escapeHtml($block->getMethodCode());
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
?>

<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= /* @noEscape */ $code ?>"
          style="display:none">
    <input type="hidden" name="payment[public_hash]" id="<?= /* @noEscape */ $code ?>_public_hash" value="">
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_number">
            <span><?= $escaper->escapeHtml(__('Credit Card Number')) ?></span>
        </label>
        <div class="admin__field-control">
            <iframe data-ifields-id="card-number" data-ifields-placeholder="Card Number"
                    src="https://cdn.cardknox.com/ifields/3.1.2508.1401/ifield.htm" frameBorder="0"
                    height="35"></iframe>
            <input data-ifields-id="card-number-token" name="payment[xCardNum]" type="hidden"/>
        </div>
    </div>
    <div class="field-date admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_expiration">
            <span><?= $escaper->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_expiration" name="payment[cc_exp_month]"
                    class="admin__control-select admin__control-select-month validate-cc-exp required-entry">
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option value="<?= $escaper->escapeHtmlAttr($k) ?>"
                            <?php if ($k == $ccExpMonth): ?>selected="selected"<?php endif ?>>
                        <?= $escaper->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?= /* @noEscape */ $code ?>_expiration_yr" name="payment[cc_exp_year]"
                    class="admin__control-select admin__control-select-year required-entry">
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option value="<?= $k ? $escaper->escapeHtmlAttr($k) : '' ?>"
                            <?php if ($k == $ccExpYear): ?>selected="selected"<?php endif ?>>
                        <?= $escaper->escapeHtml($v) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <?php if ($block->hasVerification()): ?>
        <div class="field-number required admin__field _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_cid">
                <span><?= $escaper->escapeHtml(__('Card Verification Number')) ?></span>
            </label>
            <div class="admin__field-control">
                <iframe data-ifields-id="cvv" data-ifields-placeholder="CVV"
                        src="https://cdn.cardknox.com/ifields/3.1.2508.1401/ifield.htm" frameBorder="0"
                        height="35"></iframe>
                <input data-ifields-id="cvv-token" name="payment[xCVV]" type="hidden"/>
                <label id="ifieldsError" data-ifields-id="card-data-error"></label>
            </div>
        </div>
    <?php endif; ?>
    <div class="admin__field admin__field-option">
        <div class="admin__field-control">
            <input type="checkbox"
                name="payment[is_active_payment_token_enabler]"
                value="1"
                id="<?= /* @noEscape */ $code ?>_enable_vault"
                class="admin__control-checkbox"/>
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_enable_vault">
                <span><?= $escaper->escapeHtml(__('Save for later use.')) ?></span>
            </label>
        </div>
    </div>
</fieldset>
