<?php
/**
 * Copyright © 2024 Cardknox Development Inc. All rights reserved.
 * See LICENSE for license details.
 */

use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
$details = $block->getData(TokenUiComponentProviderInterface::COMPONENT_DETAILS);
$icon = $block->getData('icons')[$details['type']];
$id = $escaper->escapeHtml($block->getData('id'));
?>
<?php
$publicHash = $block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH);
$code = $block->getData('code');
?>
<div data-mage-init='{
        "CardknoxDevelopment_Cardknox/vault": {
            "container": "payment_<?= /* @noEscape */ $id ?>",
            "publicHash": "<?= $escaper->escapeHtmlAttr($publicHash) ?>",
            "code": "<?= $escaper->escapeHtmlAttr($code) ?>"
            }
    }' id="payment_<?= /* @noEscape */ $id ?>" class="admin__field">
    <div class="admin__field-control control">
        <input type="radio" id="token_switcher_<?= /* @noEscape */ $id ?>" name="payment[token_switcher]"/>
        <img src="<?= $escaper->escapeUrl($icon['url']) ?>"
             width="<?= $escaper->escapeHtmlAttr($icon['width']) ?>"
             height="<?= $escaper->escapeHtmlAttr($icon['height']) ?>"
             class="payment-icon">
        <span><?= $escaper->escapeHtml(__('ending')) ?></span>
        <span><?= $escaper->escapeHtml($details['maskedCC']) ?></span>
        <span><?= $escaper->escapeHtml(__('expires')) ?></span>:
        <span><?= $escaper->escapeHtml($details['expirationDate']) ?></span>)
    </div>
</div>
