<?php
/**
 * @see \CardknoxDevelopment\Cardknox\Block\Adminhtml\System\Config\ApplePay\Info
 * @var \CardknoxDevelopment\Cardknox\Block\Adminhtml\System\Config\ApplePay\Info $block
 */

?>
<div class="payflow-settings-notice">
    <strong class="important-label"><?= $block->escapeHtml(__('Important: ')) ?></strong>
    <p> Please complete the Apple Pay Domain Registration <a target="_blank" href="https://portal.solapayments.com/settings/gateway-settings/payment-methods">here</a> prior to enabling Sola Apple Pay.
    </p>
</div>
